#!/bin/bash

set -e

if [ -n "$BARHACK_LINT_ID" ]; then
  if [[ `head -n 1 /home/barhack/files/$BARHACK_LINT_ID/status.txt` == 'PENDING' ]]; then
    echo 'FAILED' > /home/barhack/files/$BARHACK_LINT_ID/status.txt
  fi
fi